### PR TITLE
[ PYTHON ] - Josewebdev2000 challenge 2 solution

### PR DESCRIPTION
**Pull request by josewebdev2000**
Solution to the second challenge of File I/O. I used pandas to read data and I used specific filtering techniques in order to find the number of songs in key of E.

### CODE REVIEW

**Comment by l-white** [comment]
Could you add your second and third contributions to a different file? I am getting tracekback errors when I try to run them.

**Comment by josewebdev2000** [comment]
Sorry for not replying earlier. It is completely fine if you add my solutions for my third and second contributions to a different file.

**Comment by l-white** [comment]
@josewebdev2000 No worries, but if you want your contributions to count, we'll need you to make the changes or get everything to run properly in your current folder.

**Comment by l-white** [comment]
@josewebdev2000 Changes were requested 3 weeks ago; none were forthcoming, so we're closing the PR due to no response.

**Pull request closed without merging**
