### PR TITLE
[Spring-Boot-App] [jar packaging] Unlock Music Insights: Spotify Data Logger

### PR DESCRIPTION
**Pull request by hanisntsolo**
The Java-based solution is based on an in-memory database which is usually used in industry-wide practices (with real databases), and people can consult it to include the approach in their projects.

### CODE REVIEW

**Comment by l-white** [comment]
@hanisntsolo Please resolve class file issues and place any dependencies within your submission, not a global folder.

**Comment by hanisntsolo** [comment]
> @hanisntsolo Please resolve class file issues and place any dependencies within your submission, not a global folder.

Hi @l-white can you please elaborate on what changes are needed, class file issues never heard of em. Can you please advise.

**Comment by l-white** [comment]
@hanisntsolo Certainly -- I'll do my best to advise on how to get your project to pass. It is possible that this runs all right on your computer, but I also need to run it successfully on my computer. With Java, a project won't run unless everything, including dependencies, are set up correctly. Including a README in your project directory with the required dependencies and instructions on how to run it from either an IDE or the command line will help us evaluate your results.

In addition, you have some files that were placed outside of your submission, and those would need to be included within your submission, which is likely adding to the issues.

I am going to link to three projects for File I/O in Java that passed successfully so that you can see how they're set up and how to modify your contribution:
https://github.com/zero-to-mastery/file-io/pull/101
https://github.com/zero-to-mastery/file-io/pull/81
https://github.com/zero-to-mastery/file-io/pull/28

**Comment by hanisntsolo** [comment]
@l-white  Requesting Review. Changes incorporated.

**Comment by l-white** [comment]
@hanisntsolo Your dependencies are still outside of your submissions folder. Please see my comment on your other PR. I am closing this because it has the same issue, not because any rules of our server were violated.

**Pull request closed without merging**
