### PR TITLE
_Spotify Data Logger [JAVA]

### PR DESCRIPTION
**Pull request by hanisntsolo**
Done all the three challenges outlined in this repo.

The project consists of a script that reads data from a CSV file (spotify-2023.csv) and performs the following tasks.
Load Spotify data from the CSV file.
Create a folder for your project with your github handler.
Complete at least one of the challenges below.
Add your folder with your project to the submissions folder of this repo.
Include the script that runs your file.
Note: the project must successfully complete one of the challenges below to qualify for as a submission.

Challenges
Write a script to identify the number of songs in the file. DONE
Write a script that identify the number of songs in the key of E. DONE
Count the occurrences of values in a specified column (e.g., artist names) and determine the most common value. DONE

### CODE REVIEW

**Comment by hanisntsolo** [comment]
@MattCSmith @l-white @notAnkur  Please check this as I am expecting a merge.

**Comment by hanisntsolo** [comment]
@l-white @MattCSmith @wmporter @kennithnichol @beneyal  Can you please merge this i have been anticipating a merge since yesterday.

**Comment by kennithnichol** [comment]
I understand that you're anxious about a merge @hanisntsolo . You **must** exercise patience. Especially when contributing to open source projects. We will get to your PR in due course. All PRs will be evaluated and marked or merged during the event.

There are 41 PRs on this project now, and there are 2 other projects that we're overlooking for this event. It takes time (our time) which we volunteer freely.

**Comment by hanisntsolo** [comment]
> I understand that you're anxious about a merge @hanisntsolo . You **must** exercise patience. Especially when contributing to open source projects. We will get to your PR in due course. All PRs will be evaluated and marked or merged during the event.
> 
> 
> 
> There are 41 PRs on this project now, and there are 2 other projects that we're overlooking for this event. It takes time (our time) which we volunteer freely.

Okay thank you for your efforts!!🙌

**Comment by hanisntsolo** [comment]
@kennithnichol Please give feedback why it was closed without merge. I may work and fix the shortcomings.

**Comment by kennithnichol** [comment]
This was closed due to the reasons detailed by @l-white and @MattCSmith on discord.

Persistent pinging, impatience, and a disregard for the nature of the open source volunteers time.

**Pull request closed without merging**
