### PR TITLE
[RUST] Added API in Rust

### PR DESCRIPTION
**Pull request by RedHoodJT1988**

### CODE REVIEW

**Comment by l-white** [comment]
@RedHoodJT1988 There is a mismatched closing delimiter that is throwing an error. Please make this correction and commit it to this branch.

**Comment by RedHoodJT1988** [comment]
> @RedHoodJT1988 There is a mismatched closing delimiter that is throwing an error. Please make this correction and commit it to this branch.

Hello, I am not sure what line the error is on. I am going to rewrite the file. Still learning Rust so perhaps I missed something that is new to me per the syntax of Rust. Thank you.

**Comment by l-white** [comment]
@RedHoodJT1988 It looks like the first set of errors is cleared up, but I now have a few more errors with regards to mismatched types, so unfortunately, cannot merge this yet. Please feel free to give it another try. We also have a couple of contributions in Rust from S.Khalar, which you can take a look at.

**Comment by RedHoodJT1988** [comment]
Just wanted to check if the errors were cleared up for you on your end now. :)

**Comment by l-white** [comment]
Sorry, the code does not run, so we are closing the pull request

**Pull request closed without merging**
