### PR TITLE
[ PYTHON ] - Python for E / Total # Songs - Pandas

### PR DESCRIPTION
**Pull request by T-Crypt**
Resubmission -- Added submission folder -- Synced main branch

### CODE REVIEW

**Comment by l-white** [comment]
@T-Crypt The filepath in your contribution is not defined properly. Please make this change and commit it to this branch.

**Comment by T-Crypt** [comment]
> @T-Crypt The filepath in your contribution is not defined properly. Please make this change and commit it to this branch.

Do you mean I'm missing the "-" in my name? I added the files to submissions.

**Comment by T-Crypt** [comment]
Updated.

**Comment by l-white** [comment]
@T-Crypt It appears that your last few commits are empty. You're almost there, but there are still a few modifications needed.

First, add this line directly below your pandas import: 
df = pd.read_csv('./spotify-2023.csv', encoding='ISO-8859-1')

Second, move your print statements outside your functions so they will run. Add the following on their own lines:
print("Number of songs: ", len(df))
print(count_songs_in_key_of_e(df))

**Comment by T-Crypt** [comment]
@l-white Changes have been made -- updated and simplified the script 

Print outside of the functions and added df = below  import pandas

**Pull request merged**
