### PR TITLE
[TYPESCRIPT] hacktoberfest submission

### PR DESCRIPTION
**Pull request by elciosato**
This is the Hacktoberfest Challenge Submission

### CODE REVIEW

**Comment by l-white** [comment]
@elciosato Thanks for your submission; however, I get a type error when I run this. Please make the correction and add the change to your branch.

**Comment by l-white** [comment]
@elciosato I'm sorry, but we still cannot merge this. There are a number of import errors. Please try to compile and run on your machine first.

Also, there is no need to add the README that already exists for this project. The purpose of your adding a README would be to indicate if there are any dependencies we need to install to run your project and a script to run your project. See the README on this project for more information.

**Comment by elciosato** [comment]
Hi @l-white,

I'm sorry, but I'm unable to reproduce the error on my machine. 
I followed your suggestion, and there are no errors.

I cloned the project into a different folder, followed the same steps, and encountered no errors:

```bash
cd ./file-io/submissions/elciosato/
npm install
# Run
npm run file-io

# Build and run
npm run build
npm run start
```
Thank you

**Comment by l-white** [comment]
@elciosato Worked perfectly. Thanks for your contribution and your patience.

**Comment by elciosato** [comment]
I'm glad to hear it worked. Thank you very much.

**Pull request merged**
