### PR TITLE
task completed all results updated for hacktoberfest

### PR DESCRIPTION
**Pull request by ishi12121**

### CODE REVIEW

**Comment by l-white** [comment]
This is a relatively simple project, and your contribution has 36k lines of code. I'd love to review it but we need to keep things simple for Hacktoberfest. I encourage you to resubmit a project that follows the guidelines we have outlined. It should be a simple file I/O project that does not require an API.

**Comment by ishi12121** [comment]
I have  made the requested changes

**Comment by l-white** [comment]
@ishi12121 There are several class errors being returned. Please make the necessary corrections and push your changes.

**Comment by ishi12121** [comment]
Please check now. I have tried commenting each part to see if the errors still persist. If there is still a problem, please let me know.

**Pull request merged**
