### PR TITLE
[JAVA] Submission to Hacktoberfest

### PR DESCRIPTION
**Pull request by Jayaswini**

### CODE REVIEW

**Comment by l-white** [comment]
@Jayaswini Please create a folder for your submission and put it in the submissions folder. This was added directly to submissions -- it needs to be within its own folder. See the README for details.

**Comment by Jayaswini** [comment]
I have made the changes as requested. I have created a folder and added my
submission to it. Please do look into my PR.

**Comment by l-white** [comment]
@Jayaswini There isn't a way to build your project. Please a build configuration file, for example, build.gradle for Gradle or pom.xml for Maven.

**Comment by Jayaswini** [comment]
There is a pom.xml file for the project. I have included that in my
submission, can you please check once

**Comment by l-white** [comment]
@Jayaswini Thank you. Someone else will review your PR because I am unfortunately not set up to run Spring Boot easily.

**Comment by hanisntsolo** [comment]
hi jayaswinin maybe you can package the spring-boot-app as jar and can ask l-white to run at her end. to see the challenges complete.

**Comment by mithusingh32** [comment]
The file path isn't OS-agnostic. 

Only way I could get this to work was modify the path. I think you should make the file path agnostic to the OS. It should be simple as changing `"src\\main\\resources\\spotify-2023.csv"` to `"src/main/resources/spotify-2023.csv"`

**Comment by Jayaswini** [comment]
I have changed the file path. Do I need to package it as a jar and push it
again

**Comment by hanisntsolo** [comment]
It should, as it is a spring app and @l-white may be required to run it to verify whether really the challengers are done.

**Pull request merged**
