### PR TITLE
[JAVA] Single Java Class Csv Parser | All challenges complete

### PR DESCRIPTION
**Pull request by hanisntsolo**
#If you want to run directly -  use the following command : 

`javac SpotifyDataParser.java && java SpotifyDataParser
`
Just make sure you are on the base directory hanintsolo-plain-script.

or more simply just do : 

`java SpotifyDataParser.java 
`
Note : make sure that you have compiled the SpotifyDataParser.java using javac

### CODE REVIEW

**Comment by l-white** [comment]
@hanisntsolo So there is still an issue with your contribution. Any dependencies that you have need to go within your submission folder. You are attempting to add these to the overall repository. They should not be added there because they are part of your project. Because this will probably not run correctly just by moving them, I am going to suggest that you close this pull request and open another one once you have the project set up correctly.

Please note: I am going to close your other pull request that is open on this project, not because any rules were violated but because it is the same project with the same issue.

Please also close this pull request once you have read my comments so you can try again. Simply moving your dependencies into the correct folder will likely not solve the issue: it needs to be set up properly within your submissions folder.

Screen Shot 2023-10-08 at 8 56 22 AM

**Comment by hanisntsolo** [comment]
Oh these are the culprits. Let me fix them. Actually this is a huge projects with different people pushing different languages so there was an oversight.

Fixing it.

**Comment by hanisntsolo** [comment]
> @hanisntsolo So there is still an issue with your contribution. Any dependencies that you have need to go within your submission folder. You are attempting to add these to the overall repository. They should not be added there because they are part of your project. Because this will probably not run correctly just by moving them, I am going to suggest that you close this pull request and open another one once you have the project set up correctly.
> 
> 
> 
> Please note: I am going to close your other pull request that is open on this project, not because any rules were violated but because it is the same project with the same issue.
> 
> 
> 
> Please also close this pull request once you have read my comments so you can try again. Simply moving your dependencies into the correct folder will likely not solve the issue: it needs to be set up properly within your submissions folder.
> 
> 
> 
> Screen Shot 2023-10-08 at 8 56 22 AM

These are autogenerated by the IDE let me fix it as it was an oversight I was developing internally and pushing out from submission hence this oversight happened.

**Comment by hanisntsolo** [comment]
Done finally @l-white requesting review.

**Comment by hanisntsolo** [comment]
Changes completed removed autogenerate .idea from intellijeIDEA and incorporated changes @l-white .

**Comment by l-white** [comment]
@hanisntsolo Your code runs. Great job!

**Comment by hanisntsolo** [comment]
> @hanisntsolo Your code runs. Great job!

Thank you @l-white. I feel a bit sorry for being very impatient earlier but it feels good now.

**Pull request merged**
